In [1]:
import numpy as np
import glob
import cv2
d={}

In [2]:
data_dir='UCF-101/*/*'
data_list=glob.glob(data_dir)
img_size=(56,56)
frame_number=20
sample_step=4
data=np.empty([1,frame_number,img_size[0],img_size[1],3])
label=np.empty([1,])
fps=25
sample_step=4
npz_order=0
num_cat = 4
video_per_cat=100


print(len(data_list))
print(data.shape)


538
(1, 20, 56, 56, 3)


In [3]:
with open("classInd.txt") as f:
    for line in f:
       (key, val) = line.split()
       d[int(key)-1] = val

In [4]:
one_hot_array = np.zeros((num_cat*video_per_cat,num_cat))

In [5]:
videonumkeeptrack = np.zeros((1,num_cat))


In [6]:
arraynum = 0
for num, video in enumerate(data_list):
    read_video = False
    print (num, video)
    if(not arraynum<(num_cat*video_per_cat)):
        break
    for key, videoname in d.items():    # for name, age in dictionary.iteritems():  (for Python 2.x)
        if (videoname in video) and (key<num_cat):
            if(videonumkeeptrack[0][key]<video_per_cat):
                videonumkeeptrack[0][key] = videonumkeeptrack[0][key]+1
                print(videonumkeeptrack)
                print(video)
                read_video = True
                one_hot_array[arraynum][key]=1
                arraynum = arraynum+1
    if(read_video):
        cap = cv2.VideoCapture(video)
        #fps = cap.get(cv2.CAP_PROP_FPS)
        total_frame=cap.get(cv2.CAP_PROP_FRAME_COUNT)
        #print(total_frame)
        sample=np.empty([1,1,img_size[0],img_size[1],3])
        for i in range(sample_step*frame_number):
            if (i%sample_step)==0:
                ret, frame = cap.read()
                if ret==False:
                    prev=sample[0,-1].reshape(1,1,img_size[0],img_size[1],3)
                    sample=np.append(sample,prev,axis=1)
                else:
                    cropped_frame=cv2.resize(frame,(img_size[0],img_size[1]))
                    cropped_frame=cropped_frame.reshape(1,1,img_size[0],img_size[1],3)
                    sample=np.append(sample,cropped_frame,axis=1)
        sample=sample[0,1:]
        sample=sample.reshape([1,frame_number,img_size[0],img_size[1],3])
        #print("one sample shape: {}".format(sample.shape))
        data=np.append(data,sample,axis=0)
#         del sample,cropped_frame



print("data shape；{}".format(data.shape))

0 UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g15_c03.avi
[[1. 0. 0. 0.]]
UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g15_c03.avi
1 UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g24_c05.avi
[[2. 0. 0. 0.]]
UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g24_c05.avi
2 UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g11_c03.avi
[[3. 0. 0. 0.]]
UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g11_c03.avi
3 UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g22_c01.avi
[[4. 0. 0. 0.]]
UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g22_c01.avi
4 UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c03.avi
[[5. 0. 0. 0.]]
UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c03.avi
5 UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g03_c04.avi
[[6. 0. 0. 0.]]
UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g03_c04.avi
6 UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g25_c05.avi
[[7. 0. 0. 0.]]
UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g25_c05.avi
7 UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g05_c07.avi
[[8. 0. 0. 0.]]
UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g05_c07.avi
8 UCF-101/ApplyEyeMakeup

66 UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g07_c07.avi
[[67.  0.  0.  0.]]
UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g07_c07.avi
67 UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g04_c04.avi
[[68.  0.  0.  0.]]
UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g04_c04.avi
68 UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g09_c02.avi
[[69.  0.  0.  0.]]
UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g09_c02.avi
69 UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g09_c06.avi
[[70.  0.  0.  0.]]
UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g09_c06.avi
70 UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g18_c05.avi
[[71.  0.  0.  0.]]
UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g18_c05.avi
71 UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g07_c05.avi
[[72.  0.  0.  0.]]
UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g07_c05.avi
72 UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g25_c07.avi
[[73.  0.  0.  0.]]
UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g25_c07.avi
73 UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g22_c03.avi
[[74.  0.  0.  0.]]
UCF-101/ApplyEyeMakeup/v_ApplyEyeMak

160 UCF-101/Archery/v_Archery_g23_c02.avi
[[100.   0.  15.   1.]]
UCF-101/Archery/v_Archery_g23_c02.avi
161 UCF-101/Archery/v_Archery_g13_c07.avi
[[100.   0.  16.   1.]]
UCF-101/Archery/v_Archery_g13_c07.avi
162 UCF-101/Archery/v_Archery_g15_c02.avi
[[100.   0.  17.   1.]]
UCF-101/Archery/v_Archery_g15_c02.avi
163 UCF-101/Archery/v_Archery_g20_c01.avi
[[100.   0.  18.   1.]]
UCF-101/Archery/v_Archery_g20_c01.avi
164 UCF-101/Archery/v_Archery_g16_c04.avi
[[100.   0.  19.   1.]]
UCF-101/Archery/v_Archery_g16_c04.avi
165 UCF-101/Archery/v_Archery_g12_c01.avi
[[100.   0.  20.   1.]]
UCF-101/Archery/v_Archery_g12_c01.avi
166 UCF-101/Archery/v_Archery_g19_c03.avi
[[100.   0.  21.   1.]]
UCF-101/Archery/v_Archery_g19_c03.avi
167 UCF-101/Archery/v_Archery_g13_c06.avi
[[100.   0.  22.   1.]]
UCF-101/Archery/v_Archery_g13_c06.avi
168 UCF-101/Archery/v_Archery_g21_c02.avi
[[100.   0.  23.   1.]]
UCF-101/Archery/v_Archery_g21_c02.avi
169 UCF-101/Archery/v_Archery_g20_c05.avi
[[100.   0.  24.   1.]

239 UCF-101/Archery/v_Archery_g09_c01.avi
[[100.   0.  94.   1.]]
UCF-101/Archery/v_Archery_g09_c01.avi
240 UCF-101/Archery/v_Archery_g12_c03.avi
[[100.   0.  95.   1.]]
UCF-101/Archery/v_Archery_g12_c03.avi
241 UCF-101/Archery/v_Archery_g09_c04.avi
[[100.   0.  96.   1.]]
UCF-101/Archery/v_Archery_g09_c04.avi
242 UCF-101/Archery/v_Archery_g17_c02.avi
[[100.   0.  97.   1.]]
UCF-101/Archery/v_Archery_g17_c02.avi
243 UCF-101/Archery/v_Archery_g17_c04.avi
[[100.   0.  98.   1.]]
UCF-101/Archery/v_Archery_g17_c04.avi
244 UCF-101/Archery/v_Archery_g06_c02.avi
[[100.   0.  99.   1.]]
UCF-101/Archery/v_Archery_g06_c02.avi
245 UCF-101/Archery/v_Archery_g15_c06.avi
[[100.   0. 100.   1.]]
UCF-101/Archery/v_Archery_g15_c06.avi
246 UCF-101/Archery/v_Archery_g01_c01.avi
247 UCF-101/Archery/v_Archery_g20_c07.avi
248 UCF-101/Archery/v_Archery_g05_c02.avi
249 UCF-101/Archery/v_Archery_g25_c06.avi
250 UCF-101/Archery/v_Archery_g05_c05.avi
251 UCF-101/Archery/v_Archery_g20_c04.avi
252 UCF-101/Archery/

336 UCF-101/ApplyLipstick/v_ApplyLipstick_g20_c04.avi
[[100.  45. 100.   1.]]
UCF-101/ApplyLipstick/v_ApplyLipstick_g20_c04.avi
337 UCF-101/ApplyLipstick/v_ApplyLipstick_g22_c02.avi
[[100.  46. 100.   1.]]
UCF-101/ApplyLipstick/v_ApplyLipstick_g22_c02.avi
338 UCF-101/ApplyLipstick/v_ApplyLipstick_g03_c01.avi
[[100.  47. 100.   1.]]
UCF-101/ApplyLipstick/v_ApplyLipstick_g03_c01.avi
339 UCF-101/ApplyLipstick/v_ApplyLipstick_g05_c02.avi
[[100.  48. 100.   1.]]
UCF-101/ApplyLipstick/v_ApplyLipstick_g05_c02.avi
340 UCF-101/ApplyLipstick/v_ApplyLipstick_g24_c04.avi
[[100.  49. 100.   1.]]
UCF-101/ApplyLipstick/v_ApplyLipstick_g24_c04.avi
341 UCF-101/ApplyLipstick/v_ApplyLipstick_g19_c03.avi
[[100.  50. 100.   1.]]
UCF-101/ApplyLipstick/v_ApplyLipstick_g19_c03.avi
342 UCF-101/ApplyLipstick/v_ApplyLipstick_g19_c01.avi
[[100.  51. 100.   1.]]
UCF-101/ApplyLipstick/v_ApplyLipstick_g19_c01.avi
343 UCF-101/ApplyLipstick/v_ApplyLipstick_g01_c04.avi
[[100.  52. 100.   1.]]
UCF-101/ApplyLipstick/v_Ap

409 UCF-101/BabyCrawling/v_BabyCrawling_g05_c03.avi
[[100. 100. 100.   5.]]
UCF-101/BabyCrawling/v_BabyCrawling_g05_c03.avi
410 UCF-101/BabyCrawling/v_BabyCrawling_g10_c03.avi
[[100. 100. 100.   6.]]
UCF-101/BabyCrawling/v_BabyCrawling_g10_c03.avi
411 UCF-101/BabyCrawling/v_BabyCrawling_g18_c03.avi
[[100. 100. 100.   7.]]
UCF-101/BabyCrawling/v_BabyCrawling_g18_c03.avi
412 UCF-101/BabyCrawling/v_BabyCrawling_g24_c04.avi
[[100. 100. 100.   8.]]
UCF-101/BabyCrawling/v_BabyCrawling_g24_c04.avi
413 UCF-101/BabyCrawling/v_BabyCrawling_g01_c02.avi
[[100. 100. 100.   9.]]
UCF-101/BabyCrawling/v_BabyCrawling_g01_c02.avi
414 UCF-101/BabyCrawling/v_BabyCrawling_g18_c06.avi
[[100. 100. 100.  10.]]
UCF-101/BabyCrawling/v_BabyCrawling_g18_c06.avi
415 UCF-101/BabyCrawling/v_BabyCrawling_g09_c03.avi
[[100. 100. 100.  11.]]
UCF-101/BabyCrawling/v_BabyCrawling_g09_c03.avi
416 UCF-101/BabyCrawling/v_BabyCrawling_g16_c01.avi
[[100. 100. 100.  12.]]
UCF-101/BabyCrawling/v_BabyCrawling_g16_c01.avi
417 UCF-

476 UCF-101/BabyCrawling/v_BabyCrawling_g19_c03.avi
[[100. 100. 100.  72.]]
UCF-101/BabyCrawling/v_BabyCrawling_g19_c03.avi
477 UCF-101/BabyCrawling/v_BabyCrawling_g22_c07.avi
[[100. 100. 100.  73.]]
UCF-101/BabyCrawling/v_BabyCrawling_g22_c07.avi
478 UCF-101/BabyCrawling/v_BabyCrawling_g21_c01.avi
[[100. 100. 100.  74.]]
UCF-101/BabyCrawling/v_BabyCrawling_g21_c01.avi
479 UCF-101/BabyCrawling/v_BabyCrawling_g23_c04.avi
[[100. 100. 100.  75.]]
UCF-101/BabyCrawling/v_BabyCrawling_g23_c04.avi
480 UCF-101/BabyCrawling/v_BabyCrawling_g18_c05.avi
[[100. 100. 100.  76.]]
UCF-101/BabyCrawling/v_BabyCrawling_g18_c05.avi
481 UCF-101/BabyCrawling/v_BabyCrawling_g11_c03.avi
[[100. 100. 100.  77.]]
UCF-101/BabyCrawling/v_BabyCrawling_g11_c03.avi
482 UCF-101/BabyCrawling/v_BabyCrawling_g04_c03.avi
[[100. 100. 100.  78.]]
UCF-101/BabyCrawling/v_BabyCrawling_g04_c03.avi
483 UCF-101/BabyCrawling/v_BabyCrawling_g19_c01.avi
[[100. 100. 100.  79.]]
UCF-101/BabyCrawling/v_BabyCrawling_g19_c01.avi
484 UCF-

In [7]:
boundary = num_cat*video_per_cat
print(boundary)
raw_data = data[:boundary,...]
raw_data = raw_data/255.0
print(raw_data.shape)

400
(400, 20, 56, 56, 3)


/home/jetherng/keras/lib/python3.5/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


In [8]:
print(raw_data)

[[[[[0.         0.         0.        ]
    [0.         0.         0.        ]
    [0.         0.         0.        ]
    ...
    [0.         0.         0.        ]
    [0.         0.         0.        ]
    [0.         0.         0.        ]]

   [[0.         0.         0.        ]
    [0.         0.         0.        ]
    [0.         0.         0.        ]
    ...
    [0.         0.         0.        ]
    [0.         0.         0.        ]
    [0.         0.         0.        ]]

   [[0.         0.         0.        ]
    [0.         0.         0.        ]
    [0.         0.         0.        ]
    ...
    [0.         0.         0.        ]
    [0.         0.         0.        ]
    [0.         0.         0.        ]]

   ...

   [[0.         0.         0.        ]
    [0.         0.         0.        ]
    [0.         0.         0.        ]
    ...
    [0.         0.         0.        ]
    [0.         0.         0.        ]
    [0.         0.         0.        ]]

   [[0.         

In [9]:
np.random.seed(42)
index=np.arange(len(one_hot_array))
np.random.shuffle(index)
print (index)
raw_data=raw_data[index]
one_hot_array=one_hot_array[index]

[209 280  33 210  93  84 329  94 266 126   9 361  56  72 132  42 278 376
 231 385  77  15 391 271   0 396 114 225 262 104 395 193 261  57 232 116
 113 342 158 141 381  55  76  25  82 382 148 181  22 173  46 321 338  70
 374  39 223 172  30 152 124 294 255  78 101  31 352 268 394  73 320 140
   5  45 388 246 227 369 176 289   3  18 202 250 274  63 248 301 108  90
 233 335 118 220 180 314 373 380 239  75 247 110  16  66 153   7  19 137
 355 349 131 387 292 386 297  60  79 285 305 281 157 109  17 347  24 175
 351 332 167 245 311 145 258 177 119 194 229 265 218 307  36 139 291 155
 196 284  59 111 165 363   6 333 275 150  10 192 103  81 316 398 375 208
 286 168 353  89 377 163 147 228  92  69 123  96 143 326  97 238  68  23
  37 144 122 182  67 198 324 219 317 195 125 146 371  86 336 340 337 354
 334 302 183 203 283 211 282 129  38  11 325 185 222 112 179 327 299 117
 368 277 384 287 362 164 253 136 154 199 197 392   2 204 115 234 237  26
 120 357 224 360 378 350 379 127  74 322  29  83 38

In [10]:
np.savez_compressed('npz_data1/ucf_classes/data_{}_{}.npz'.format(npz_order,img_size[0]), arr_0=raw_data)
np.savez_compressed('npz_data1/ucf_classes/label_{}_{}.npz'.format(npz_order,img_size[0]), arr_0=one_hot_array)
#npz_order+=1
raw_data=np.empty([1,frame_number,img_size[0],img_size[1],3])
one_hot_array=np.empty([1,num_cat])

In [11]:
print(raw_data.shape)
print(one_hot_array.shape)

(1, 20, 56, 56, 3)
(1, 4)
